#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done


levels=$(cat /sys/class/power_supply/BAT*/capacity)

sum=0

for level in $levels; do 
	sum=$(($sum + $level))
done

if [ "$sum" -lt 20 ]; then 
	systemctl hibernate
fi
