#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done
. /home/functions 

only_root

if [ $1 -lt 1 -o $1 -gt 15 ] 
then 
	msg_error "BAD ARGUMENT!!!"
	exit 1 
fi
echo $1 > /sys/class/backlight/acpi_video0/brightness
