#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions

only_root 

if [ $(get_distro) != "gentoo" ] 
then 
	msg_error "Only on Gentoo based systems."
fi

chown -R paludisbuild:paludisbuild /usr/portage/distfiles
#chown -R paludisbuild:paludisbuild /zajedno/Distfiles

#chown -R paludisbuild:paludisbuild /var/tmp/ccache

chown -R paludisbuild:paludisbuild /var/tmp/paludis
chmod g+rwx /var/tmp/paludis/

#chown -R paludisbuild:paludisbuild /paketi/Linux/Paludis/binaries /zajedno/paketi/Linux/Paludis/binaries /zajedno/zajedno-sdb/paketi/Linux/Paludis/binaries
