#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions

only_root

if [ -d /boot/slackware ] 
then 
	cd /boot/slackware/
else
	echo "/boot/slackware does not exists"
	echo "Please enter path to your place where are config System.map and vmlinuz kernel image"
	read KERNELSPATH
	cd $KERNELSPATH
fi

echo "Please enter kernel version"
read VERSION_KERNEL

for FILE in System.map vmlinuz config
do 
	echo "$FILE"
	rm -rf $FILE
	ln -s $FILE-huge-$VERSION_KERNEL $FILE
done
