#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions

only_root

echo ""
free -mt
echo ""

DIRS="/bin /lib64 "
DIRS+="/opt "
DIRS+="/usr/bin /usr/lib64 "
DIRS+="/usr/local/bin /usr/local/lib64"

msg_info "Size of cached data: $(du ${DIRS} -hsc)"

echo ""
msg_info "Caching dirs: ${DIRS}"
msg_info "This can be long Time..."
find  ${DIRS}  -type f -exec cat '{}' > /dev/null \;

echo ""
msg_info "Caching done."

echo ""
free -mt
echo ""
