#!/bin/sh

. /home/functions 

only_root 

echo ""
free -mt
echo ""

echo ""
msg_warn "Free pagecache, dentries and inodes, can long works, please patience!"
echo ""
#sync; sysctl -w vm.drop_caches=3; sysctl -w vm.drop_caches=0
sync; echo 1 > /proc/sys/vm/drop_caches;echo 2 > /proc/sys/vm/drop_caches;echo 3 > /proc/sys/vm/drop_caches
echo ""

echo ""
free -mt
echo ""
