#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

OPTIONS="rw,users"

if fdisk -l | grep /dev/sdb1 | awk '{print $7}' | grep NTFS > /dev/null; then 
	OPTIONS="$OPTIONS,flush"
fi

mount /dev/sdb1 /media/usb -o $OPTIONS

chmod -R 777 /media/usb/

