#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

case $1 in 
	start) 
		systemctl start nginx
		systemctl start php-fpm@5.5.service
		systemctl start mysqld
		;; 
	stop) 
		systemctl stop nginx
		systemctl stop php-fpm@5.5.service
		systemctl stop mysqld
		;; 
	restart) 
		systemctl restart nginx
		systemctl restart php-fpm@5.5.service
		systemctl restart mysqld
		;; 
	*) echo "Usage: $0 start|stop|restart" ;; 
esac
