#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

if [ $(get_distro) != "gentoo" ] 
then 
	msg_error "Only on Gentoo based systems."
fi
cd /usr/local/portage

rm -rf app-paludis/plop 
cd app-paludis
svn co https://svn.keksbude.net/repos/keks-overlay/app-paludis/plop/
