#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

if [ ! "$(get_distro)" = "gentoo" ] 
then 
	msg_error "Only on Gentoo based systems."
fi
PKGS=$(qlist -IC virtualbox-modules broadcom)

emerge -a $PKGS @x11-module-rebuild
#cave resolve $PKGS
#echo -n "is it ok??? "
#read Q
#if [ $Q = "y" ]
#then 
#	cave resume
#fi 
