#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

if [ $1 = "--help" ]; then 
	echo "Usage: $0 backupdir"
	exit 0
fi

cd /me/data/

DATE=$(date +%Y-%m-%d)

SAVE_DIR="$1"

tar -cpPf "$SAVE_DIR/save-data-${DATE}.tar.gz" --exclude MIT --exclude Videos/Youtube --exclude Videos/Movies .
