#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

USER=$(whoami)

if [ $USER = "root" ] 
then
	passwd
	echo -n "Your username "
	read USERNAME
	passwd $USERNAME
	echo -n "Do you have login user? "
	read LOGINUSER
	if [ $LOGINUSER = "y" ] 
	then 
		echo -n "Enter login username "
		read LOGINUSERNAME
		passwd $LOGINUSERNAME
	fi
fi
