#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

echo "Backup to /backup ?" 
read p
$DATE=$(date +%d-%m-%Y)
tar -cvPpjf /backup/system-$DATE.tar.bz2 / --exclude /proc --exclude /sys --exclude /dev --exclude /home --exclude /stage* --exclude /portage* --exclude /media --exclude /mnt --exclude /backup --exclude /data --exclude /me 
/home/scripts/end
