#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 

SAVE_DIR="/me/save"
SAVE_ZAJEDNO_DIR="$SAVE_DIR/me/"
SAVE_ARCHIVE="/data/save-archive/"

#Clean /me archives 
find  $SAVE_ZAJEDNO_DIR -mtime +365 -delete

#Clean save-archive
find $SAVE_ARCHIVE -mtime +365 -delete


