#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

. /home/functions 

only_root 


if [ $(get_distro) != "gentoo" ] 
then 
	msg_error "Only on Gentoo based systems."
fi
emerge --sync
#cave sync 

# Update overlays 
layman -S 
emerge --regen
# Update eix 
eix-update

#/home/sbin/plop-sync

#echo -n "Do you want to upgrade portage? "
#read PORTAGE_UPGRADE
#if [ $PORTAGE_UPGRADE = "y" ] 
#then 
#	#emerge portage
#	cave -x resolve portage
#fi
#echo "Do you want to upgrade paludis? "
#read UPGRADE_PALUDIS
#if [ $UPGRADE_PALUDIS = "y" ] 
#then 
#	cave -x resolve paludis
#fi
echo "" >> /var/mylogs/portage.log
#echo "" >> /var/mylogs/paludis.log
#date >> /var/mylogs/portage.log
DATE=$(date)
echo "$DATE Updated packages..." >> /var/mylogs/portage.log
