#!/bin/sh

. /home/functions 

only_root 

USER=$(whoami)

if [ $USER = "root" ] 
then
	passwd
	echo -n "Your username "
	read USERNAME
	passwd $USERNAME
	echo -n "Do you have login user? "
	read LOGINUSER
	if [ $LOGINUSER = "y" ] 
	then 
		echo -n "Enter login username "
		read LOGINUSERNAME
		passwd $LOGINUSERNAME
	fi
fi
