#!/bin/sh

SHORTOPTS=":h"
LONGOPTS="help"
OPTS=$(getopt -o $SHORTOPTS --longoptions $LONGOPTS -n "$0" -- "$@")
eval set -- "$OPTS"

while [ $# -gt 0 ]; do
    case $1 in
        -h|--help)
            echo "Usage: "
            echo "Description"
            echo 
            #list of options following
            echo -e "-h \t print this message"
        	exit 0
        ;;
        --)
           shift
           break
        ;;

    esac
    shift
done

if [ $(uname -r | grep -i arch | wc -l) -gt 0 -a -e "$(which pacman)" ] 
then 
	echo "ArchLinux"
fi
if [ -e "$(which emerge 2> /dev/null)" ] 
then 
	echo "Gentoo"
fi
